version: '3.8'
services:
  node-app:
    build:
      context: .
      target: production
    #      args:
#        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm start